spring:
  application:
    name: lotto-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:23306/point_service?serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/lotto_service?serverTimezone=Asia/Seoul
    username: lotto_service
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          userCreationEvent-in-0:
            consumer:
              configuration:
                value:
                  deserializer: msa.pseudo.lotto.lottoservice.kafka.deserializer.CustomJsonDeserializer
          producer-out-0:
            producer:
              configuration:
                value:
                  serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #        streams:
      #          binder:
      #            configuration:
      #              spring.json.trusted.packages: '*'
      bindings:
        userCreationEvent-in-0:
          destination: userCreation
          contentType: application/json
#          consumer:
#            use-native-decoding: true
        producer-out-0:
          destination: lottoResult
          contentType: application/json



#spring.kafka.consumer.properties.spring.json.trusted.packages: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8083