spring:
  application:
    name: client
  thymeleaf:
    cache: false
#    enabled: true
#    prefix: classpath:/templates/
#    suffix: .html

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka