spring:
  application:
    name: point-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:23306/point_service?serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/point_service?serverTimezone=Asia/Seoul
    username: point_service
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  cloud:
    function:
      definition: userCreationEventConsumer;lottoResultEventConsumer;
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          userCreationEventConsumer-in-0:
            consumer:
              configuration:
                value:
                  deserializer: msa.pseudo.lotto.pointservice.kafka.deserializer.CustomJsonDeserializer
          lottoResultEventConsumer-in-0:
            consumer:
              configuration:
                value:
                  deserializer: msa.pseudo.lotto.pointservice.kafka.deserializer.CustomJsonDeserializer
      bindings:
        userCreationEventConsumer-in-0:
          destination: userCreation
          contentType: application/json
        lottoResultEventConsumer-in-0:
          destination: lottoResult
          contentType: application/json



#spring.kafka.consumer.properties.spring.json.trusted.packages: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8082